-- 1. 用户表（新增RBAC角色字段，兼容原有结构）
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'STUDENT' COMMENT 'STUDENT/TEACHER/ADMIN'
);

-- 2. 门禁地点表（保留原有字段，无改动）
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    qr_token VARCHAR(255)
);

-- 3. 门禁事件记录表（保留原有字段，无改动）
CREATE TABLE IF NOT EXISTS access_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    location_id BIGINT,
    access_time TIMESTAMP,
    method VARCHAR(255),
    allowed BOOLEAN,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES locations(id)
);

-- 4. 课程表（保留原有字段，补充外键关联教师）
CREATE TABLE IF NOT EXISTS COURSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    CODE VARCHAR(255),
    teacher_id BIGINT,
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);

-- 5. 课程时段表（保留原有字段，完善外键关联）
CREATE TABLE IF NOT EXISTS SESSIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COURSE_ID BIGINT,
    LOCATION_ID BIGINT,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES locations(id)
);

-- 6. 学生课程关联表（保留原有字段，无改动）
CREATE TABLE IF NOT EXISTS STUDENT_COURSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID BIGINT,
    COURSE_ID BIGINT,
    FOREIGN KEY (STUDENT_ID) REFERENCES users(id),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID)
);

-- 7. 考勤表（保留原有字段，完善外键关联）
CREATE TABLE IF NOT EXISTS ATTENDANCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID BIGINT,
    SESSION_ID BIGINT,
    CHECK_IN_TIME TIMESTAMP,
    CHECK_OUT_TIME TIMESTAMP,
    STATUS VARCHAR(255),
    FOREIGN KEY (STUDENT_ID) REFERENCES users(id),
    FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS(ID)
);

-- 8. 新增临时密码表（支撑临时密码门禁功能）
CREATE TABLE IF NOT EXISTS TEMP_CODES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(6) NOT NULL UNIQUE,
    location_id BIGINT NOT NULL,
    owner_id BIGINT,
    expires_at TIMESTAMP NOT NULL,
    remaining_uses INT NOT NULL,
    used_at TIMESTAMP,
    FOREIGN KEY (location_id) REFERENCES locations(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);