CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    qr_token VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS access_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    location_id BIGINT,
    access_time TIMESTAMP,
    method VARCHAR(255),
    allowed BOOLEAN
);
CREATE TABLE IF NOT EXISTS COURSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    CODE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SESSIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COURSE_ID BIGINT,
    LOCATION_ID BIGINT,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STUDENT_COURSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID BIGINT,
    COURSE_ID BIGINT
);

CREATE TABLE IF NOT EXISTS ATTENDANCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID BIGINT,
    SESSION_ID BIGINT,
    CHECK_IN_TIME TIMESTAMP,
    CHECK_OUT_TIME TIMESTAMP,
    STATUS VARCHAR(255)
);
